# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# subtract.py
# Created on: 2022-03-03 14:09:04.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy


# Local variables:
Recreation__Open_Space_and_Protected_Natural_Areas_ = "Recreation,_Open_Space_and_Protected_Natural_Areas_"
Conservation_Recreation = "Conservation_Recreation"
Developable_UGS_shp = "C:\\Users\\Jli\\Desktop\\Vancouver Env\\Developable UGS.shp"

# Process: Erase
arcpy.Erase_analysis(Recreation__Open_Space_and_Protected_Natural_Areas_, Conservation_Recreation, Developable_UGS_shp, "")

